server:
  rootPath: /api/*
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080

allowedOrigins:
    - "*"

template: Hello, %s!
defaultName: Strange
score: 0

#db settings
database:
  #the name of db, h2 in our case
  driverClass: org.h2.Driver
  #username
  user: sa
  #password
  password: 
  #JDBC URL
  url: jdbc:h2:./target/DBconn